### ISSUE TITLE
For a single-image test.

### ISSUE THREAD

**Issue by theseung** [cxliu0/PET#15]
Hello!
This model requires the use of a DataLoader for testing.

I want to test a single image and get the results, how can I do it?

Please help me.

**Comment by cxliu0** [comment]
For single-image testing, you can discard the dataloader in [engine.py](https://github.com/cxliu0/PET/blob/main/engine.py#L141), and directly load a single image following the data processing in [SHA.py](https://github.com/cxliu0/PET/blob/main/datasets/SHA.py#L64)

**Comment by tejasri19** [comment]
I tried to to infer the trained model on an image of 1536 x 1152 resolution. I get the following error

> Traceback (most recent call last):
  File "eval.py", line 208, in <module>
    main(args)
  File "eval.py", line 172, in main
    outputs = model(samples)
  File "/home/tejasri/anaconda3/envs/new/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tejasri/P2P/PET_paddy/models/pet.py", line 304, in forward
    out = self.test_forward(samples, features, pos, **kwargs)   
  File "/home/tejasri/P2P/PET_paddy/models/pet.py", line 357, in test_forward
    outputs = self.pet_forward(samples, features, pos, **kwargs)
  File "/home/tejasri/P2P/PET_paddy/models/pet.py", line 327, in pet_forward
    outputs_sparse = self.quadtree_sparse(samples, features, context_info, **kwargs)
  File "/home/tejasri/anaconda3/envs/new/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tejasri/P2P/PET_paddy/models/pet.py", line 166, in forward
    hs = self.transformer(encode_src, src_pos_embed, mask, pqs, img_shape=samples.tensors.shape[-2:], **kwargs)
  File "/home/tejasri/anaconda3/envs/new/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tejasri/P2P/PET_paddy/models/transformer/prog_win_transformer.py", line 139, in forward
    hs = self.decoder_forward(query_feats, query_embed, 
  File "/home/tejasri/P2P/PET_paddy/models/transformer/prog_win_transformer.py", line 97, in decoder_forward
    query_embed_win = window_partition(query_embed_, window_size_h=dec_win_h, window_size_w=dec_win_w)
  File "/home/tejasri/P2P/PET_paddy/models/transformer/utils.py", line 33, in window_partition
    raise ValueError(f"Window size (h={window_size_h}, w={window_size_w}) must be divisible by the tensor dimensions (H={H}, W={W})")
ValueError: Window size (h=8, w=16) must be divisible by the tensor dimensions (H=3, W=128)


I tried to apply resize transform of (256,256) and (256, 128) and do not work. The error is still there.

@cxliu0 @theseung Can you share how the error can be solved

**Comment by cxliu0** [comment]
Please refer to [test_single_image.py](https://github.com/cxliu0/PET/blob/main/test_single_image.py) for single image testing. You need to specify the image and model path, see [this line](https://github.com/cxliu0/PET/blob/main/test_single_image.py#L159).

**Comment by tejasri19** [comment]
Thank you.
